### PR TITLE
Update docs (after Docker)

### PR DESCRIPTION
**Pull request by cuducos**
After merging #163 I felt like reorganizing the documentation a bit.

Basically moved stuff around to keep Docker instructions altogether. Also gave more importance to the documentation os the settings.

### CODE REVIEW

**Comment by lipemorais** [comment]
It's Awesome!

Do you think that would be good have some instructions in docker hub explaining a little more about each Jarbas image?

**Comment by cuducos** [comment]
I haven't thought about it… any suggestions?

**Comment by cuducos** [comment]
I haven't thought about it… any suggestions?

**Comment by lipemorais** [comment]
May this is not applicable for our case, so feel free to disagree. 

What I have in my mind is have an explanation based in great Dockerfiles in Docker Hub like [postgres](https://hub.docker.com/_/postgres/) and [python](https://hub.docker.com/_/python/) with just what make sense for us. Like:
-  Add a more meaningful short description for Jarbas images
- Where get help about the images(_I think that this will be specially helpful for new contributors that don't know about Docker_)
- Where Dockerfile that generates this images can be found

**Comment by jtemporal** [comment]
I think as far as the Readme file goes, this PR looks pretty good so I'm merging it...
=)

**Pull request merged**
