### PR TITLE
Add sample data

### PR DESCRIPTION
**Pull request by cuducos**
This might be useful to easily get started with a development environment — as suggested in #120.

Also useful [when Rosie and the toolbox are temporally not available](https://github.com/datasciencebr/serenata-toolbox/issues/19) — isn't it @jtemporal?

### CODE REVIEW

**Comment by jtemporal** [comment]
YESSS \o/ thank you @cuducos

**Comment by gomex** [comment]
YEAH! 👍

**Comment by gomex** [comment]
When you merge it I will change the seed make target

**Comment by cuducos** [comment]
> When you merge it I will change the seed make target

Really? This is just sample data. Not the full dataset. I expect to use it just to easily build a development environment, not to replace the whole dataset download and creation (that should be delegated to Rosie).

**Comment by gomex** [comment]
@cuducos it is about development mode :) I will create a new Makefile target.

**Comment by jtemporal** [comment]
@cuducos and @gomex merged =)

**Comment by gomex** [comment]
Great news! Thanks @jtemporal

**Pull request merged**
