### PR TITLE
[WIP] Optimize data Import (Fix #125)

### LINKED ISSUE #125: Optimize data import
Nowadays first we import all reimbursements (`python manage.py reimbursements …`) and later we update these reimbursements with irregularities/suspicions (`python manage.py irregularities …`).

If we bring in `pandas` we could merge both datasets and import both datasets together in one command.

An extra would be that we could have the script drafted in [this markdown](https://github.com/datasciencebr/jarbas/blob/1939c49aa667e7984e8a53bf5fbfa3718e1d0811/contrib/sample-data/README.md) file as an actual `.py` script (since `pandas` would be added to the `requirements.txt`).

### PR DESCRIPTION
**Pull request by Guilhermeslucas**
Hi all! I was working to fix #125 . I want some feedback about the work, specially two things:
- [This part of the code](https://github.com/Guilhermeslucas/jarbas/blob/master/jarbas/core/management/commands/reimbursements.py#L18-L20) adds the irregularities path for the reimbursements command. But, in my opinion, it's weird cause, for ```reimbursements_path``` there is no need to use ```--reimbursements_path``` and, in this case, we need to use ```--irregularaties-path```.

- The identation on [this part of the code](https://github.com/Guilhermeslucas/jarbas/blob/master/jarbas/core/management/commands/reimbursements.py#L38-L42) is horrible. I want some suggestions on how to make it better.

Please, tell me everything you think I have to change!

### CODE REVIEW

**Comment by cuducos** [comment]
Hi @Guilhermeslucas! Once more we're glad to have your contribution and enthusiasm!

First of all, can you rebase this branch so it doesn't include code from other PRs (eg. #142)? Otherwise the diff from `master` is so complex that makes it impossible to do a proper code review  — and, yet, you  bring in errors from that WIP PR too ; )

Regarding your questions:

To pass `irregularities_path` without the `--xpto` or `-x`, just [don't pass the first two positional arguments](https://github.com/Guilhermeslucas/jarbas/blob/master/jarbas/core/management/commands/__init__.py#L10) ; )

The lines you highlighted you don't have to open files to pass them to Pandas's `read_ csv`. :

```python
    @property
    def reimbursements(self):
        """Returns a Generator with a Reimbursement object for each row."""
        print('Reading reimbursements dataset…')
        reimbursements = pd.read_csv(self.reimbursement_path, dtype=object).fillna('')

        print('Reading irregularities dataset…')
        irregularities = pd.read_csv(self.irregularities_path, dtype=object).fillna('')

        print('Merging datasets…')
        on = ('applicant_id', 'year', 'document_id')
        for _, row in pd.merge(reimbursements, irregularities, on=on).iterows():
            yield Reimbursement(**self.serialize(row.to_dict()))
```

Besides that, some hopefully hints:

* I would `import pandas as pd`(it's also a kind of convention within Python community)
* Use [`prospector`](https://github.com/landscapeio/prospector) to spot things you can enhance in terms of code quality ; )
* When in a unpacking (eg. what happens in the `for` loop above) you don't use one variable, you just name it `_` (it's also a convention within Python community)
* I like to add `print` (we could improve and use proper `logging`, but anyway…) to help the user knwo what's happening behind the scenes ; )

**Comment by Guilhermeslucas** [comment]
Can you give me some help rebasing? I did it just once and I'm afraid off messing up stuff.

**Comment by cuducos** [comment]
I suck at `git`, but that's how I'd do it:

1. Kind of _save_ these changes you have in branch different than master: `git checkout -b guilhermeslucas-optimize-imports-old`
1. Go to the master branch: `git checkout master`
1. Pull from the main repo: `git pull origin master -f` (maybe you have `upstream` as this repo, and `origin` as your fork, IDK), but this step is tricky because your master is ahead of the main repo master branch — not sure how to align that, I'd have to do some research; anyway the point is to have your master branch exactly as this repo's master branch ; )
1. Create a new branch based on the master: `git checkout -b guilhermeslucas-optimize-imports`
1. Cherry pick the commits from `guilhermeslucas-optimize-imports-old` to `guilhermeslucas-optimize-imports`: `git cherry-pick 0f956fd` (and repeat for all commits you want to bring on board)
1. Delete the old messed up branch: `git branch -D guilhermeslucas-optimize-imports-old`

But maybe someone more expert in `git` can help you better than that.

**Comment by Guilhermeslucas** [comment]
I'll do it soon, but hard reset m master branch with the upstream. Have you merged my past commits on a branch, different than master, right? Just to be sure i won't lose this. Thanks!

**Comment by Guilhermeslucas** [comment]
I'll close this pull request after the changes and open another one with the branch updated. Is that ok?

**Comment by cuducos** [comment]
> Have you merged my past commits on a branch, different than master, right?

Yep, they're at `cuducos-company-activity-as-json` branch now.

**Pull request closed without merging**
