### PR TITLE
Optimize dashboard performance

### PR DESCRIPTION
**Pull request by cuducos**
~Work in progress~ branch to sort out some performance issues in the dashboard from #180

### CODE REVIEW

**Comment by thiagoalencar** [comment]
I got it from https://stackoverflow.com/questions/2204058/list-columns-with-indexes-in-postgresql.
But in the pgAdmin it's easy to see.
"select
    t.relname as table_name,
    i.relname as index_name,
    array_to_string(array_agg(a.attname), ', ') as column_names
from
    pg_class t,
    pg_class i,
    pg_index ix,
    pg_attribute a
where
    t.oid = ix.indrelid
    and i.oid = ix.indexrelid
    and a.attrelid = t.oid
    and a.attnum = ANY(ix.indkey)
    and t.relkind = 'r'
    and t.relname like 'test%'
group by
    t.relname,
    i.relname
order by
    t.relname,
    i.relname;"

Return all table names,indexes, and columns.

**Comment by cuducos** [comment]
Hi @thiagoalencar,

Adapting that command to:

```
"select
t.relname as table_name,
i.relname as index_name,
array_to_string(array_agg(a.attname), ', ') as column_names
from
pg_class t,
pg_class i,
pg_index ix,
pg_attribute a
where
t.oid = ix.indrelid
and i.oid = ix.indexrelid
and a.attrelid = t.oid
and a.attnum = ANY(ix.indkey)
and t.relkind = 'r'
and t.relname like 'core_reimbursement'
group by
t.relname,
i.relname
order by
t.relname,
i.relname;"
```

I got:

```
    table_name     |                      index_name                      |    column_names
--------------------+------------------------------------------------------+---------------------
 core_reimbursement | core_reimbursement_applicant_id_dc5b4033             | applicant_id
 core_reimbursement | core_reimbursement_cnpj_cpf_9035d450                 | cnpj_cpf
 core_reimbursement | core_reimbursement_cnpj_cpf_9035d450_like            | cnpj_cpf
 core_reimbursement | core_reimbursement_congressperson_name_08c45884      | congressperson_name
 core_reimbursement | core_reimbursement_congressperson_name_08c45884_like | congressperson_name
 core_reimbursement | core_reimbursement_document_id_53a6e416_uniq         | document_id
 core_reimbursement | core_reimbursement_issue_date_1ad82d84               | issue_date
 core_reimbursement | core_reimbursement_last_update_3fee6abc              | last_update
 core_reimbursement | core_reimbursement_month_b87da546                    | month
 core_reimbursement | core_reimbursement_pkey                              | id
 core_reimbursement | core_reimbursement_receipt_fetched_f95c4dbf          | receipt_fetched
 core_reimbursement | core_reimbursement_state_9c5760b1                    | state
 core_reimbursement | core_reimbursement_state_9c5760b1_like               | state
 core_reimbursement | core_reimbursement_subquota_id_2d6a31d0              | subquota_id
 core_reimbursement | core_reimbursement_year_92263c07                     | year
(15 rows)
```

**Comment by thiagoalencar** [comment]
Good, following the query sent in the telegram group, 
"year DESC, issue_date DESC, id DESC"

From Django model, create an index with this three columns: 'index_together = ["year", "issue_date","id"]' 
Reference:https://docs.djangoproject.com/en/dev/ref/models/options/#index-together
If you wish to get better result and your queries sorts are fixed you can create index on postgresql direct and define the sorting order:
''CREATE INDEX  xxx ON core_reimbursement (year DESC,issue_date DESC, id DESC );"
Reference:https://www.postgresql.org/docs/9.0/static/indexes-ordering.html
                 https://devcenter.heroku.com/articles/postgresql-indexes

**Comment by cuducos** [comment]
> From Django model, create an index with this three columns: `index_together = ["year", "issue_date","id"]`

Sounds a good idea, gonna bring back the WIP label and test it to see if we have a better result.

> If you wish to get better result and your queries sorts are fixed you can create index on postgresql direct and define the sorting order:

That's definitively a no-go for me. This adds a lot of overhead for maintenance, provision and deploy. Also adds a lot of difficulties for the community to replicate our development and production environment.

**Comment by cuducos** [comment]
Wow! @thiagoalencar you nailed it.

Before `index_together` I timed it 5 times locally, then I applied the migration and ran it 5 times again:

| Attempt | Without `index_together` | With `index_together` |
|---|---|---|
| 1 | 14.119s | 0.077s |
| 2 | 8.867s | 0.070s |
| 3 | 9.395s | 0.068s |
| 4 | 9,969s | 0.037s |
| 5 | 8.392s | 0.040s |

**Comment by cuducos** [comment]
Ready for code review @jtemporal ; )

**Pull request merged**
