### PR TITLE
[WIP] Store company activities as JSON (Fix #124)

### LINKED ISSUE #124: Store company activities as JSONField
Nowadays each `Company` stores its main and secondary activities in a separate model (`Activity`) using a `ManyToManyField`.

I don't think it's necessary as we won't query by a company activity (at least not that frequently). Also this design makes the `python manage.py companies <companies.xz>` extremely slow because we cannot use `bulk_create` with relational tables (or can we?).

### PR DESCRIPTION
**Pull request by cuducos**
This PR puts together @Guilhermeslucas's code from #139 (that I merged to this branch) with some tweaks:

* Taylor made migrations to avoid data loss when moving forward/backward in migration history
* Fix an error I had myself injected in his PR 13931c6
* Fix tests and coverage
* Some cleanup
* Code style & minor refactors

### CODE REVIEW

**Comment by Guilhermeslucas** [comment]
@cuducos I just merged this branch with my local repository, and I'm getting an error running companies command. Is it okay there?

line 57, in serialize_activity ValueError: invalid literal for int() with base 10: '47.31-8-00'

**Comment by cuducos** [comment]
Wow. My bad. There were a few commits in my local machine yet. So sorry. Would you mind updating your branch with the commits I just pushed to GitHub at test it again? e789816 should fix it.

**Comment by Guilhermeslucas** [comment]
Now it's working, but I think we have a problem. Look the way the API is showing secondary_activities.
captura de tela de 2017-01-30 17 59 45

Is it okay or you want me to try to fix it?

**Comment by cuducos** [comment]
Nope. Surely it's not OK. I"m gonna try to reproduce the error in a test case and fix it.

**Comment by Guilhermeslucas** [comment]
@cuducos Just fixed it! It's on the last commit on my fork! In serialize_activities i added a check for null dicts.

**Comment by cuducos** [comment]
I'm afraid you partially fixed… c4e9eef fixes it in the importing but _also_ (and this is important) in the migrations. 

Unfortunately while fixing it I've found an error in the backward migration. Probably I'm gonna fix that tomorrow.

**Comment by Guilhermeslucas** [comment]
sorry, really forgot about migrations!

**Comment by Guilhermeslucas** [comment]
Let me know when you fix it, I want to merge it to another branch I'm working on! Many thanks!

**Comment by cuducos** [comment]
I haven't had time to focus on that, and I'll probably take some time to do so. I'm sorry about that — either way I'll let you know once it's fixed ; )

**Comment by Guilhermeslucas** [comment]
I'll try to fix the migrations too, in that case. Thanks a lot!

**Comment by cuducos** [comment]
That'd be great. The trick, I guess, is to change the field type (from `ManyToManyField` to `JSONField`) in the same migration — but this should be a manual migration.

I tried to combine a couple of auto-generated migration with a manual one (just to convert data forward and backward) but Django messes up the field types this way (the source code is in my PR #147). That's why I guess we'll have to manually write a single migration changing types and converting data.

**Comment by cuducos** [comment]
Closing this PR because storing it as JSON would make `CNPJ` filters _too slow_…

**Pull request closed without merging**
