### PR TITLE
Refactor Internationalization

### LINKED ISSUE #123: Break Internationalization module into smaller modules
The `Internationalization` module got too big (more than 600 LOC) and it might be a good idea to break it in smaller modules.

### PR DESCRIPTION
**Pull request by fcevado**
closes #123

### CODE REVIEW

**Comment by fcevado** [comment]
I created the PR to see if the way I'm breaking the module into submodules is Ok. If any changes are necessaries I can adapt in a early stage.

**Comment by cuducos** [comment]
I think this is a good start. I don't know how _usable_ it gets if we try to create different _constant_ files for each module (one for the search form, one from the company panel etc). Maybe it will start to get troublesome, but if it doesn't I think translations get more organized.

Just a detail I noticed: [one file ended up with all imports duplicated](https://github.com/fcevado/jarbas/blob/1f007a9ec1eafdf9d3ba7b8aebc88847cf8fd5bd/jarbas/frontend/elm/Reimbursement/Search/View.elm), ok?

**Comment by fcevado** [comment]
> I think this is a good start. I don't know how usable it gets if we try to create different constant files for each module (one for the search form, one from the company panel etc). Maybe it will start to get troublesome, but if it doesn't I think translations get more organized.

I thought of that,  I wasnt sure how to *categorize* those modules... I'll follow that.

> Just a detail I noticed: one file ended up with all imports duplicated, ok?

I didn't notice that... :disappointed_relieved:

**Comment by fcevado** [comment]
I'm update the PR, but I'm still with some doubts...

Should be doing qualified imports(to see explicit where the constants come from) or open imports(the current way I'm doing)?

Inside the Internationalization domain should be a Reimbursement subdomain or should it be everything inside Internatioanalization without separation?

**Comment by cuducos** [comment]
Good questions! I'm addressing them in a purely opinionated way (that might change with real code examples), but…

> Should be doing qualified imports(to see explicit where the constants come from) or open imports(the current way I'm doing)?

I tend to prefer _qualified imports_, but sometimes the length of the import is so long that it just doesn't make sense to be that idealistic…

> Inside the Internationalization domain should be a Reimbursement subdomain or should it be everything inside Internatioanalization without separation?

I think it makes sense to have _semantic_ sub-modules so it becomes quite obvious to look up for a specific translation. However this remembers a lot a modularization architecture that might end up in data passing through a lot of intermediaries before reaching its target — as in the module vs. stateless discussion. Therefore I tend to prefer modules and submodules but I'm not sure about the pragmatic effect of my own advise ; )

**Comment by fcevado** [comment]
> I tend to prefer qualified imports, but sometimes the length of the import is so long that it just doesn't make sense to be that idealistic…

To simplify and make smaller modules calls using qualified imports, I'm using something like that:
```elm
import Big.SubModules.List.Of.Names as Names
```

**Comment by fcevado** [comment]
I think it's finished.

**Comment by cuducos** [comment]
Wow! Way better, isn't it?

Great work, many thanks for that!

When compiling with `--warn` there is three friendly reminders from the compiler:

```
=================================== WARNINGS ===================================

-- unused import ------- ././jarbas/frontend/elm/Reimbursement/Company/Model.elm

Module `Internationalization` is unused.

5| import Internationalization exposing (translate)
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Best to remove it. Don't save code quality for later!

=================================== WARNINGS ===================================

-- unused import ----------- ././jarbas/frontend/elm/Reimbursement/Map/Model.elm

Module `Internationalization` is unused.

3| import Internationalization exposing (translate)
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Best to remove it. Don't save code quality for later!

=================================== WARNINGS ===================================

-- unused import -------------- ././jarbas/frontend/elm/Reimbursement/Update.elm

Module `Internationalization` is unused.

7| import Internationalization exposing (translate)
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Best to remove it. Don't save code quality for later!
```

Would you mind cleaning up before I merge?

**Comment by fcevado** [comment]
Done! :smiley:

**Comment by cuducos** [comment]
Yay… many thanks for this great contribution ; )

**Pull request merged**
