### PR TITLE
Delegate reimbursement import to Celery

### PR DESCRIPTION
**Pull request by cuducos**
This is a work in progress, I just created it earlier to have feedbacks. The aim, when complete, is to address part of #217.

**What is the purpose of this Pull Request?**
The purpose of this PR is make the process of importing reimbursement quicker and without manual steps as described in #217.

**What was done to achieve this purpose?**
I introduced Celery to perform some task asynchronously: that way the heavy work of the import is handled in the background.

**How to test if it really works?**

1. Install RabbitMQ _if not using Docker_ — `brew install rabbitmq` or `apt-get install rabbitmq-server` should do the job for macOS and any Debian based Linux such as Ubuntu (Docker environment is ready, no need to worry about it) 
2. Install new packages: `$ python -m pip install -U -r requirements.txt`
3. Run tests `$ python manage.py test`
4. Get Celery started: `$ celery worker --app jarbas`
5. Run reimbursement import: `$ python manage.py reimbursements <path to reimbursements.xz>`

**Who can help reviewing it?**
@jtemporal @lipemorais @davinirjr @augustogoulart @adrianomargarin

**What is out of scope**
In #217 I mentioned creating a API endpoint so Rosie can send `POST`s with reimbursement data. I think this is an issue for a new PR when this one is finished, reviewed, stable an merged.

**Next steps in this PR**

- [x] Find out why the iteration is taking so long for each CSV (`.xz`) line (either I screwed up when wiring up Celery, or the serialize step is another bottleneck; if so, a callback in Celery should be able to handle serializing and then the create/update step)
- [x] Improve documentation on the RabbitMQ and Celery parts (I added bit on the environment variable, but instructions to run Celery still missing as well as pointing RabbitMQ as a requirement)

**Next steps**

* Bring back Docker Hub images to `docker-compose.yml` after this PR is merged

### CODE REVIEW

**Comment by decko** [comment]
Testing with sample data seems Ok. Ready to Merge.

**Comment by cuducos** [comment]
> Testing with sample data seems Ok. Ready to Merge.

In PVT @decko told me that actually it wasn't working with the Celery (worker) running in a container. So we still need to fix that before considering merging it. Is that right?

**Comment by cuducos** [comment]
Ok… I'm back to this PR.

I merged the novelties from `master` branch and studied this PR a bit more to advance it further.

The `master` branch imported the sample in 34s (counting the time to start Docker containers) and this branch did it in 24s (idem). We were saving 30% of the time, which is great.

Then I moved the serialize part to the async task (42e512a). The importing command took 15s — we're saving more than 50% of time now, yay!
 
From that I think the Celery part is indeed working and this PR is good for code review and, if that's the case, merging… cc @anaschwendler

**Comment by anaschwendler** [comment]
Hello @cuducos and @decko!

I'll start testing this PR little by little and how (so it will be edited along the way):

1. Clone the repository:
```console
$ git clone git@github.com:datasciencebr/jarbas.git
```

2. Open the repo folder:
```console
$ cd jarbas
```

3. Checkout to @cuducos branch:
```console
$ git checkout -b cuducos-celery origin/cuducos-celery
```

4. Update the branch:
```console
$ git merge master
```

I'll try to run with Docker, even if its showed without, I'll try :)

**Comment by davinirjr** [comment]
Nice! Good work, people, congrats!

**Pull request merged**
